<div style="margin: 10px;" id="content_value1_tmp_table">
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FFFFFF; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FFFFFF'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#999999; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('999999'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#000000; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('000000'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FF0000; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FF0000'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FF6600; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FF6600'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FFFF00; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FFFF00'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#00FF00; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('00FF00'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#339900; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('339900'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#33CCFF; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('33CCFF'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#3300FF; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('3300FF'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#0000FF; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('0000FF'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#9900FF; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('9900FF'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FF00FF; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FF00FF'); $(this).parent().empty()"></span>
    <br>
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FFF4E2; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FFF4E2'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FFFEE0; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FFFEE0'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#EEFAE4; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('EEFAE4'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#F0F9E4; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('F0F9E4'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#E6FAFB; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('E6FAFB'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#E5EDFA; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('E5EDFA'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#E4EEFA; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('E4EEFA'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#F1E5F9; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('F1E5F9'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FCE5F5; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FCE5F5'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FEE6E4; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FEE6E4'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FDE5E3; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FDE5E3'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FFF4E2; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FFF4E2'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FFFFFF; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FFFFFF'); $(this).parent().empty()"></span>
    <br>
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FEF7C3; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FEF7C3'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FEF7C3; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FEF7C3'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#EBF6CC; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('EBF6CC'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#D5F5CC; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('D5F5CC'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#CDF5F5; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('CDF5F5'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#D0E3F2; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('D0E3F2'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#CFD5F7; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('CFD5F7'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#E3CCF6; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('E3CCF6'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#F6CDED; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('F6CDED'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FCC5CA; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FCC5CA'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FED5C3; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FED5C3'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FEE3C5; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FEE3C5'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#EEEEEE; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('EEEEEE'); $(this).parent().empty()"></span>
    <br>
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FFE9A6; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FFE9A6'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FDFBA6; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FDFBA6'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#E3F1B3; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('E3F1B3'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#BEF0B3; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('BEF0B3'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#B4F0F0; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('B4F0F0'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#B3D5F1; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('B3D5F1'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#B4BEF1; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('B4BEF1'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#CFB1EF; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('CFB1EF'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#EFB4E4; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('EFB4E4'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FEA4AE; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FEA4AE'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FFC1A6; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FFC1A6'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FFD5A5; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FFD5A5'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#D5D5D5; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('D5D5D5'); $(this).parent().empty()"></span>
    <br>
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FFE184; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FFE184'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FFF987; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FFF987'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#D6EE9A; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('D6EE9A'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#A3EB97; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('A3EB97'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#9BEBEA; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('9BEBEA'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#9CC9EA; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('9CC9EA'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#9AA9EE; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('9AA9EE'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#C099EC; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('C099EC'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#EB9BD6; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('EB9BD6'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FA8A96; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FA8A96'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FFAE88; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FFAE88'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FFC887; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FFC887'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#BFBFBF; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('BFBFBF'); $(this).parent().empty()"></span>
    <br>
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FFDA68; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FFDA68'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FFFA6A; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FFFA6A'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#CDE87F; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('CDE87F'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#94E682; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('94E682'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#82E6E4; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('82E6E4'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#84BAE6; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('84BAE6'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#8293E5; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('8293E5'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#B282E6; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('B282E6'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#E781CD; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('E781CD'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#F86E7B; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('F86E7B'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FF9A69; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FF9A69'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FEBA67; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FEBA67'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#A4A4A4; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('A4A4A4'); $(this).parent().empty()"></span>
    <br>
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FED24B; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FED24B'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FFFA6A; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FFFA6A'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#CEE97E; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('CEE97E'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#94E680; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('94E680'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#7AE6E8; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('7AE6E8'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#82BBE6; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('82BBE6'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#8293E5; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('8293E5'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#B282E6; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('B282E6'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#E583CC; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('E583CC'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#F86E7B; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('F86E7B'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FF9A6A; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FF9A6A'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FEBA69; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FEBA69'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#929292; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('929292'); $(this).parent().empty()"></span>
    <br>
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FED24B; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FED24B'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FFF94D; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FFF94D'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#C5E465; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('C5E465'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#7FE168; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('7FE168'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#69E1E0; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('69E1E0'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#68AEE1; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('68AEE1'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#6A7CE2; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('6A7CE2'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#A469E1; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('A469E1'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#E169C3; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('E169C3'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FA5263; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FA5263'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FE854C; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FE854C'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FFAC4C; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FFAC4C'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#888888; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('888888'); $(this).parent().empty()"></span>
    <br>
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FFCB2D; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FFCB2D'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FFF82C; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FFF82C'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#BAE04D; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('BAE04D'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#6ADC50; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('6ADC50'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#50DCD9; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('50DCD9'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#3792D8; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('3792D8'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#3650D9; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('3650D9'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#8537D8; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('8537D8'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#D637AE; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('D637AE'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#F6182D; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('F6182D'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FE5D0F; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FE5D0F'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#FF8F0F; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('FF8F0F'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#737373; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('737373'); $(this).parent().empty()"></span>
    <br>
	<span style="width:15px; height:15px; border:1px solid #000000; background:#EFB400; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('EFB400'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#F0E801; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('F0E801'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#A2CB27; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('A2CB27'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#45C928; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('45C928'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#28C8C6; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('28C8C6'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#2784C7; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('2784C7'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#2843C8; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('2843C8'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#7527C9; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('7527C9'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#C9279F; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('C9279F'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#E90419; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('E90419'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#F04F01; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('F04F01'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#F18000; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('F18000'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#505050; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('505050'); $(this).parent().empty()"></span>
    <br>
	<span style="width:15px; height:15px; border:1px solid #000000; background:#D29D00; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('D29D00'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#D2CB01; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('D2CB01'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#8DB31F; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('8DB31F'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#3EAE24; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('3EAE24'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#23AFAE; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('23AFAE'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#2373AE; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('2373AE'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#243BAD; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('243BAD'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#6723AE; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('6723AE'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#AF238C; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('AF238C'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#CB0617; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('CB0617'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#D24500; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('D24500'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#D27100; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('D27100'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#393939; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('393939'); $(this).parent().empty()"></span>
    <br>
	<span style="width:15px; height:15px; border:1px solid #000000; background:#967001; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('967001'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#969101; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('969101'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#658017; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('658017'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#2B7D19; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('2B7D19'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#197D7B; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('197D7B'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#19527F; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('19527F'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#192A7C; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('192A7C'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#49197D; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('49197D'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#78105F; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('78105F'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#910512; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('910512'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#973101; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('973101'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#973101; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('973101'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#151515; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('151515'); $(this).parent().empty()"></span>
    <br>
	<span style="width:15px; height:15px; border:1px solid #000000; background:#594500; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('594500'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#5A5600; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('5A5600'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#3D4D0E; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('3D4D0E'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#194B0E; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('194B0E'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#0F4B49; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('0F4B49'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#0E304B; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('0E304B'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#0F194C; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('0F194C'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#2C0E4A; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('2C0E4A'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#4A0F3B; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('4A0F3B'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#58020B; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('58020B'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#591D01; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('591D01'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#5B3302; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('5B3302'); $(this).parent().empty()"></span> 
	<span style="width:15px; height:15px; border:1px solid #000000; background:#000000; display:inline-block; cursor:pointer;" onclick="$(this).prev().prev().val('000000'); $(this).parent().empty()"></span>
    <br>
</div>